# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idveyueP6J2klOvmEKKKX-4SqEO_Q9Z8

string
"""

nama = 'dwi andini'
asal = "indonesia"

print (nama)

print (nama, asal)

print ("halo, nama saya",nama)

print ("halo, nama saya",nama, "asal saya dari", asal)

"""manipulasi string"""

print (nama, asal)

print ("halo, nama saya",nama, "asal saya dari", asal)

data_lengkap = nama + asal

print (data_lengkap)

"""string + non string"""

asal_kota = "bandar lampung"
kode_pos = 35114

asal_kota_kode_pos = asal_kota + str (kode_pos)

print (asal_kota_kode_pos)

"""perkalian string"""

asal_kota_x3 = asal_kota * 3
print (asal_kota_x3)